### PR TITLE
Improve autoupdate round 4

### PR DESCRIPTION
**Pull request by lldelisle**
Sorry I found again unexpected behaviours:
- Here the comment says that there are new updates while the new updates are for another tool: https://github.com/bgruening/galaxytools/pull/1507#issuecomment-2376724544
- Here the comment says to delete the branch while it has been deleted: https://github.com/bgruening/galaxytools/pull/1242#issuecomment-2376738404

### CODE REVIEW

**Comment by lldelisle** [comment]
Another unexpected behaviour see https://github.com/galaxyproject/planemo/issues/1478

**Comment by lldelisle** [comment]
Another 'failure': because of `| tee` to write stderr to file, the exit code of this command is always 0, even if the planemo autoupdate had an exit code of 1. I added `set -o pipefail` to keep an exit code of 1.

**Comment by bgruening** [comment]
The bot is saying I should remove the branch, but I have https://github.com/bgruening/galaxytools/pull/1354#issuecomment-2381977815

**Comment by lldelisle** [comment]
Yes, this will be solved by https://github.com/planemo-autoupdate/autoupdate/pull/39/commits/3085c45fd793ed293fb8faafbb39a5d6a3ab39b0

**Comment by lldelisle** [comment]
May I merge this? @nsoranzo @mvdbeek

**Review by nsoranzo — APPROVED** [review]

**Pull request merged**
