### PR TITLE
add an empty skip_list for lldelisle

### PR DESCRIPTION
**Pull request by lldelisle**

### CODE REVIEW

**Comment by lldelisle** [comment]
Once I've managed to make it work. I write a README for the next people...

**Comment by nsoranzo** [comment]
For future repos I think we should add a `touch FILENAME` like planemo-ci-action does, I'll make a PR.

**Comment by lldelisle** [comment]
I can put it into #31 if you want.

**Comment by nsoranzo** [comment]
> I can put it into #31 if you want.

I've got it, thanks! https://github.com/planemo-autoupdate/autoupdate/pull/32

**Pull request merged**
