### PR TITLE
add tools-lldelisle to the list

### PR DESCRIPTION
**Pull request by lldelisle**

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by lldelisle** [comment]
Apparently I need to give some access: https://github.com/planemo-autoupdate/autoupdate/actions/runs/6849702834/job/18622422282#step:8:19

**Comment by lldelisle** [comment]
I've just given write access:
image
Let see if it is sufficient.

**Comment by nsoranzo** [comment]
Yes, write access to the fork, thanks!

**Comment by lldelisle** [comment]
I forgot a skip list file...

**Pull request merged**
